### PR TITLE
Update TigerPOMDPs.jl

### PR DESCRIPTION
**Pull request by jbrea**
Shouldn't it be observation_index instead of obs_index?

### CODE REVIEW

**Comment by zsunberg** [comment]
The official function in POMDPs.jl is obs_index https://github.com/JuliaPOMDP/POMDPs.jl/blob/05c674469c9aebb667e286c81571cd1b0483bea1/src/pomdp.jl#L153

I don't think we spent a lot of time thinking about the principles behind this, but the convention is to abbreviate observation with obs in mult-word function names.

What makes you think it should be observation_index?

**Comment by jbrea** [comment]
Because of https://github.com/JuliaPOMDP/POMDPModels.jl/blob/1888fb3f16bd54d2f1882b657f80ab367174a6d5/src/POMDPModels.jl#L106

**Comment by zsunberg** [comment]
Ah I see. Good catch.

**Comment by zsunberg** [comment]
The confusion will be fixed in #31

**Comment by jbrea** [comment]
I stumbled over it when testing https://github.com/jbrea/RLEnvDiscrete.jl

**Comment by jbrea** [comment]
Great; thanks.

**Pull request closed without merging**
