### PR TITLE
TMaze bugfix: terminal states

### PR DESCRIPTION
**Pull request by mattuntergassmair**
Discovered several problems when running test set from `SparseTabularPOMDP` in POMDPModelTools.jl.
 - mapping to terminal state was not correct
 - actionindex, observationindex were missing    

For some reason, `stateindex` and `pdf` are called with an argument of type `Tuple{TMazeState, Float64}` in `test/test_tabular.jl` (POMDPModelTools.jl) and I was not able to track down where that call was initiated from. I temporarily added two functions that satisfy this interface, but they should probably be removed again before this issue is closed.

I think the transition matrix violates the assumption that a terminal state cannot be escaped (check conditions based on `d.reset` in the `transition` function)

### CODE REVIEW

**Comment by rejuvyesh** [comment]
Not many people seem to use `TMaze` so it has coderotted a bit.

**Comment by zsunberg** [comment]
@mattuntergassmair Thanks a bunch!! We should not have that `Tuple{TMazeState, Float64}`. I will track it down

**Comment by mattuntergassmair** [comment]
> @mattuntergassmair Thanks a bunch!! We should not have that `Tuple{TMazeState, Float64}` call. I will track it down

Thanks, that would be great! For some reason the stacktrace for those calls didn't seem to be super useful so I couldn't find out what was going on under the hood.

**Comment by zsunberg** [comment]
Ok, I think this is fine to merge as soon as the tests pass

**Pull request merged**
