### PR TITLE
Faster SimpleGridWorld Transition

### PR DESCRIPTION
**Pull request by WhiffleFish**
Heap allocated `MVector`'s used previously sometimes became a bottleneck in planning due to garbage collection.

This implementation is entirely stack allocated, pushing GC time to a consistent 0.0%.

The only hangup for merging this would be maintainability and implementation simplicity.

I also added tests to make sure that the distributions yielded by both this transition function and the previous one are the same.

## Benchmark
```julia
using POMDPs, POMDPModels, BenchmarkTools

mdp = SimpleGridWorld()
s = GWPos(1,1)
a = :up

@benchmark transition($mdp, $s, $a)
```

### Before
```julia
BenchmarkTools.Trial: 10000 samples with 995 evaluations.
 Range (min … max):  27.848 ns …   2.645 μs  ┊ GC (min … max):  0.00% … 98.16%
 Time  (median):     29.774 ns               ┊ GC (median):     0.00%
 Time  (mean ± σ):   39.566 ns ± 151.996 ns  ┊ GC (mean ± σ):  23.50% ±  6.02%

         ▁███▆▄▂                                                
  ▂▂▃▄▄▄▆████████▇▆▅▄▃▃▃▃▃▃▃▃▃▃▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▁▂▂ ▃
  27.8 ns         Histogram: frequency by time         38.2 ns <

 Memory estimate: 176 bytes, allocs estimate: 3.
```

### After
```julia
BenchmarkTools.Trial: 10000 samples with 998 evaluations.
 Range (min … max):  17.368 ns … 41.249 ns  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     17.452 ns              ┊ GC (median):    0.00%
 Time  (mean ± σ):   17.507 ns ±  0.482 ns  ┊ GC (mean ± σ):  0.00% ± 0.00%

   ▅ █ ▆ ▅ ▃                                                  ▁
  ██▁█▁█▁█▁█▁█▄▁▃▁▄▁▄▁▁▁▄▁▁▁▁▄▁▆▁▇▁▆▁▅▄▁▅▁▅▁▄▁▅▁▅▄▁▅▁▃▁▄▁▄▁▅▆ █
  17.4 ns      Histogram: log(frequency) by time      18.7 ns <

 Memory estimate: 0 bytes, allocs estimate: 0.
```

### CODE REVIEW

**Comment by zsunberg** [comment]
This also works nowadays: #94 :)

**Comment by WhiffleFish** [comment]
Woah is that documented anywhere?

Why does that work? Compiler magic?

**Comment by zsunberg** [comment]
I'm not sure where/if it is documented, but I think the compiler is now able to avoid allocations for any mutable object that does not ever leave the function it is allocated in. I found it out from @narijauskas last week.

Should I just merge #94 in lieu of this, or is there any reason to still consider this one?

**Comment by WhiffleFish** [comment]
Hmm okay, it doesn't seem to be the case for *any* mutable object. But yes, absolutely just merge #94. It achieves everything this PR aims to do, but in a significantly simpler way.

**Pull request closed without merging**
